---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.port: 5601
    elasticsearch.hosts: [ "http://elasticsearch:9200" ]
    elasticsearch.username: "kibana_system"
    elasticsearch.password: "aakhrif"
