{
 "title": "backend health monitoring",
 "description": "checking the backend services health",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "auth-service",
   "type": "gauge",
   "description": "health check",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"auth-service:3001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "chat-service",
   "type": "gauge",
   "description": "health check",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"chat-service:3004\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "game-service",
   "type": "gauge",
   "description": "health check",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"app-game-service-1:3006\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "notifications-service",
   "type": "gauge",
   "description": "health check",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"notification-service:3005\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "user-service",
   "type": "gauge",
   "description": "health check",
   "gridPos": { "h": 7, "w": 5, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"user-service:3002\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "auth-service",
   "type": "gauge",
   "description": "health check",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"auth-service:3001\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api-gateway",
   "type": "gauge",
   "description": "health check",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"app-api-gateway-1:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}