global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
  - job_name: 'es_exporter'
    static_configs:
      - targets: ['es_exporter:9114']

# need to add more services to monitor like nginx / backend(all the services)
# need to setup alert manager system and alert rules
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['<node1-ip>:9100', '<node2-ip>:9100']