FROM node:alpine3.21

COPY package*.json ./

RUN npm i

COPY . .

# CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy  && npm run start"]
CMD ["sh", "-c", "npx prisma generate && npx prisma db push && npx prisma db seed && npm run start"]