apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*.log
      json.keys_under_root: true
      json.add_error_key: true
      ignore_older: 72h
      scan_frequency: 10s

    output.logstash:
      hosts: ["logstash.elk.svc.cluster.local:5044"]
