filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/*.log
    json.keys_under_root: true         # Flatten JSON to top-level fields
    json.add_error_key: true           # Helps with debugging if JSON parsing fails
    ignore_older: 72h                  # Optional: ignore stale files
    scan_frequency: 10s                # Check for new logs every 10s

output.logstash:
  hosts: ["logstash:5044"]