---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.13.4
        args: ["-c", "/usr/share/filebeat/filebeat.yml", "-e"]
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: logs
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: filebeat-config
        configMap:
          name: filebeat-config
      - name: logs
        persistentVolumeClaim:
          claimName: elk-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
  namespace: elk
spec:
  selector:
    app: filebeat
  ports:
    - protocol: TCP
      port: 5044
      targetPort: 5044
  type: ClusterIP