FROM node:18-alpine

RUN apk add --no-cache openssl

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

EXPOSE 3005

CMD ["sh", "-c", "npx prisma db push --accept-data-loss && npm run start"]