---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: transcendence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: n1ghtm4r3e/trandandan_auth-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: transcendence-config
          volumeMounts:
            - name: auth-db
              mountPath: /home/auth.db
            - name: auth-logs
              mountPath: /home/logs
      volumes:
        - name: auth-db
          hostPath:
            path: /home/databases
            type: Directory
        - name: auth-logs
          hostPath:
            path: /home/logs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: transcendence
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP