---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: transcendence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: n1ghtm4r3e/trandandan_chat-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              value: "3004"
            - name: DATABASE_PATH
              value: file:/home/databases/chats.db
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service:3005
          volumeMounts:
            - name: chat-db
              mountPath: /home/databases
            - name: chat-logs
              mountPath: /home/logs
      volumes:
        - name: chat-db
          hostPath:
            path: /home/databases
            type: Directory
        - name: chat-logs
          hostPath:
            path: /home/logs
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: transcendence
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP