Vagrant.configure("2") do |config|
    # Define a common base configuration for all VMs
    config.vm.box = "ubuntu/focal64"  # Ubuntu 20.04
  
    # Define the master node
    config.vm.define "k3s-master" do |master|
      master.vm.hostname = "master-node"
      master.vm.network "private_network", ip: "192.168.56.10"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
      master.vm.provision "shell", path: "k3s-master.sh"
    end
  
    # Define the first worker node
    config.vm.define "k3s-worker1" do |worker1|
      worker1.vm.hostname = "app-node"
      worker1.vm.network "private_network", ip: "192.168.56.11"
      worker1.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      worker1.vm.provision "shell", path: "k3s-worker.sh", args: ["192.168.56.10"]
    end
  
    # Define the second worker node
    config.vm.define "k3s-worker2" do |worker2|
      worker2.vm.hostname = "elk-node"
      worker2.vm.network "private_network", ip: "192.168.56.12"
      worker2.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      worker2.vm.provision "shell", path: "k3s-worker.sh", args: ["192.168.56.10"]
    end

    # Define the third worker node
    config.vm.define "k3s-worker3" do |worker3|
      worker3.vm.hostname = "prometheus-node"
      worker3.vm.network "private_network", ip: "192.168.56.13"
      worker3.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      worker3.vm.provision "shell", path: "k3s-worker.sh", args: ["192.168.56.10"]
    end
  end