name: transcendence CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}
      REGISTRY: docker.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PAT: ${{ secrets.PAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build all images with Makefile
        run: |
          IMAGE_TAG=${{ env.IMAGE_TAG }} make

      - name: Push Images
        run: |
          docker push n1ghtm4r3e/trandandan_api-gateway:latest
        #  docker push $DOCKER_USERNAME/trandandan_auth-service:$IMAGE_TAG
        #  docker push $DOCKER_USERNAME/trandandan_user-service:$IMAGE_TAG
        #  docker push $DOCKER_USERNAME/trandandan_chat-service:$IMAGE_TAG

      - name: Update K8s deployment image tags
        run: |
          sed -i "s|\(trandandan_api-gateway:\).*|\1$IMAGE_TAG|" k8s/manifests/app.yaml

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "ci@github.com"

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          git add k8s/manifests/*.yaml
          git commit -m "ci: update image tags to $IMAGE_TAG" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push


# need to add tests