name: transcendence CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY: docker.io
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build all images with Makefile
        run: make
      
      # Alternative approach if you know your specific services
      - name: Push specific images (alternative)
        run: |
          docker push n1ghtm4r3e/trandandan_api-gateway:latest
          docker push n1ghtm4r3e/trandandan_auth-service:latest
          docker push n1ghtm4r3e/trandandan_user-service:latest
          docker push n1ghtm4r3e/trandandan_chat-service:latest
        if: true

# need to add tests and push images to dockerhub and add a deployement phase with gitOps tools (argoCD) and k8s
